Repository Kernel360/KFE3-bootup-tooMuchTask, pull requests merged in 2025-06, with the labels that each got.

#29 Create styles.ts
  src/components/Category/styles.ts
Labels: feature

#34 InputToggle 컴포넌트 제작
  src/components/Input/InputCheckBox/style.ts
  src/components/Input/InputText/styles.ts
  src/components/Input/InputToggle/index.tsx
  src/components/Input/InputToggle/style.ts
Labels: feature

#40 Storybook 추가
  .storybook/main.ts
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/Accordion/style.ts
  src/components/Card/index.tsx
  src/components/Card/styles.ts
  src/components/Chip/styles.ts
  src/stories/components/Accordion/Accordion.stories.ts
  src/stories/components/Card/Card.stories.tsx
Labels: docs

#50 fix: common-components 리펙토링, storybook 추가
  apps/docs/stories/Avatar.stories.tsx
  apps/docs/stories/Badge.stories.tsx
  apps/docs/stories/Bage.stories.tsx
  apps/docs/stories/Button.stories.tsx
  apps/docs/stories/index.stories.tsx
  packages/ui/src/components/common/Avatar.tsx
  packages/ui/src/components/common/Badge.tsx
  packages/ui/src/components/common/Button.tsx
Labels: refactor, feature
